Repository Intracto/buildozer, pull requests merged in 2019-09, with the labels that each got.

#3 RFS
  README.md
  lib/gulp/css.js
  package-lock.json
  package.json
Labels: feature

#7 Add copy functionality
  README.md
  gulpfile.js
  lib/gulp/copy.js
  package-lock.json
  package.json
Labels: feature

#8 Concatenate multiple `.js` files
  .buildozerrc
  README.md
  gulpfile.js
  lib/gulp/js.js
  package-lock.json
  package.json
Labels: feature

#11 Simplify `require()`s
  gulpfile.js
  lib/gulp/clean.js
  lib/gulp/config.js
  lib/gulp/copy.js
  lib/gulp/css.js
  lib/gulp/image.js
  lib/gulp/js.js
Labels: cleanup

#12 BrowserSync implementation
  .buildozerrc
  README.md
  gulpfile.js
  lib/gulp/clean.js
  lib/gulp/css.js
  lib/gulp/image.js
  lib/gulp/js.js
  package-lock.json
  package.json
Labels: feature

#13 Documentation improvements
  .github/CONTRIBUTING.md
  README.md
Labels: documentation

#15 Add commands to bin file
  bin/buildozer.js
  lib/error.js
Labels: bug

#16 Only use plumber on watch
  lib/gulp/css.js
  lib/gulp/image.js
  lib/gulp/js.js
Labels: bug

#24 Converted long parameter function to destructed parameters object.
  gulpfile.js
  lib/gulp/css.js
  lib/gulp/image.js
  lib/gulp/js.js
Labels: improvement
