Repository Intracto/buildozer, pull requests merged in 2020-02, with the labels that each got.

#110 Remove glob patterns from stylelint config
  gulpfile.js
  lib/gulp/configs.js
Labels: bug

#113 Add ESLint support
  gulpfile.js
  lib/gulp/configs.js
  lib/gulp/js.js
  package-lock.json
  package.json
  test/eslint/.eslintrc.json
  test/eslint/dest/js/main.js
  test/eslint/js/main.js
  test/fail-eslint/.eslintrc.json
  test/fail-eslint/js/main.js
  test/fail-tests.js
Labels: feature

#114 Update documentation
  README.md
Labels: documentation

#117 Add fix option
  README.md
  lib/gulp/css.js
  lib/gulp/js.js
  package-lock.json
  package.json
  test/fail-stylelint/.stylelintrc
Labels: feature

#118 Add update notifier
  bin/buildozer.js
  package-lock.json
  package.json
Labels: enhancement

#120 Switch environment with env parameter
  README.md
  gulpfile.js
  package.json
  test/env/dest/css/main.css
  test/env/dest/css/main.css.map
  test/env/dest/js/all.js
  test/env/dest/js/concat/test.js
  test/env/dest/js/concat/test2.js
  test/env/dest/js/test.js
  test/env/js/concat/test.js
  test/env/js/concat/test2.js
  test/env/js/test.js
  test/env/scss/dir/_import.scss
  test/env/scss/main.scss
Labels: feature

#121 Config rule per extension
  README.md
  lib/.buildozerrc
  lib/gulp/css.js
  lib/gulp/image.js
  package.json
  test/config-search/nested/dest/css/main.css
  test/css/.buildozerrc
  test/css/dest/css/main.css
  test/css/scss/main.css
Labels: performance

#122 Drop node 8 support
  .github/workflows/test.yml
  package.json
Labels: breaking change

#36 Removed opinionated postcss plugin
  README.md
  lib/gulp/css.js
  package-lock.json
  package.json
  test/config-search/dest/css/main.css
  test/config-search/nested/dest/css/main.css
  test/config-search/nested/postcss.config.js
  test/config-search/nested/scss/main.scss
  test/config-search/scss/main.scss
  test/default/dest/css/main.css
  test/default/scss/main.scss
  test/env/dest/css/main.css
  test/env/dest/css/main.css.map
  test/env/scss/main.scss
Labels: breaking change

#123 Change dest path to dist and scss key to css
  README.md
  gulpfile.js
  lib/.buildozerrc
  lib/gulp/configs.js
  lib/gulp/css.js
  test/config-search/css/dir/_import.scss
  test/config-search/css/main.scss
  test/config-search/css/subdir/file.scss
  test/config-search/dist/css/main.css
  test/config-search/dist/css/subdir/file.css
  test/config-search/dist/img/test.jpg
  test/config-search/dist/img/test.png
  test/config-search/dist/img/test.svg
  test/config-search/dist/js/all.js
  test/config-search/dist/js/concat/test.js
  test/config-search/dist/js/concat/test2.js
  test/config-search/dist/js/test.js
  test/config-search/nested/.buildozerrc
  test/config-search/nested/css/main.scss
  test/config-search/nested/dist/css/main.css
  test/config-search/nested/dist/img/test.jpg
  test/config-search/nested/dist/img/test.png
  test/config-search/nested/dist/img/test.svg
  test/config-search/nested/dist/js/all.js
  test/config-search/nested/dist/js/concat/test.js
  test/config-search/nested/dist/js/concat/test2.js
  test/config-search/nested/dist/test.txt
  test/config-search/nested/dist/test2.txt
  test/config-search/nested/vendor/.buildozerrc
  test/config-search/vendor/.buildozerrc
  test/copy/.buildozerrc
  test/copy/dist/test.txt
  test/css/css/main.css
  test/css/dist/css/main.css
  test/default/css/dir/_import.scss
  test/default/css/main.scss
  test/default/dist/css/main.css
  test/default/dist/img/test.jpg
  test/default/dist/img/test.png
  test/default/dist/img/test.svg
  test/default/dist/js/all.js
  test/default/dist/js/concat/test.js
  test/default/dist/js/concat/test2.js
  test/default/dist/js/test.js
  test/env/css/dir/_import.scss
  test/env/css/main.scss
  test/env/dist/css/main.css
  test/env/dist/css/main.css.map
  test/env/dist/js/all.js
  test/env/dist/js/concat/test.js
  test/env/dist/js/concat/test2.js
  test/env/dist/js/test.js
  test/eslint/dist/js/main.js
  test/fail-stylelint/css/main.scss
  test/sass-module/css/_buttons.scss
  test/sass-module/css/main.scss
  test/sass-module/dist/css/main.css
  test/stylelint/css/main.scss
  test/stylelint/dist/css/main.css
Labels: breaking change

#127 Use plugins array
  lib/gulp/image.js
  package.json
  test/img/.buildozerrc
  test/img/dist/img/test.jpg
  test/img/dist/img/test.svg
  test/img/img/test.jpg
  test/img/img/test.svg
Labels: bug

#130 Fix browsersync stream
  lib/gulp/css.js
  lib/gulp/image.js
  lib/gulp/js.js
Labels: bug
